//
// Created by 30225 on 2023/7/26.
//

#ifndef MCENGINE_FAKE_HASHEDSTRING_H
#define MCENGINE_FAKE_HASHEDSTRING_H


//This header template file is generated by Disassembler.

class HashedString {
public:
    //Methods
//    HashedString(unsigned long long, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >);
//    HashedString(HashedString&&);
//    HashedString(char const*);
//    HashedString(unsigned long long, char const*);
//    HashedString(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&);
//    HashedString();
//    HashedString(HashedString const&);
//    HashedString(std::nullptr_t);
//    ~HashedString();
//    void operator!=(HashedString const&) const;
//    void getHash() const;
//    void operator=(HashedString&&);
//    void operator=(HashedString const&);
//    void isEmpty() const;
//    void getEmptyString();
//    void operator<(HashedString const&) const;
//    void getString() const;
//    void empty() const;
//    void computeHash(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&);
//    void operator==(HashedString const&) const;
   void clear();
//    void computeHash(char const*);

//public:
//    //Objects
//    static HashedString * defaultErrorValue;
};//HashedString




//fake区
extern void (*fake_HashedString_HashedString)(HashedString *, char *const);
extern const char *(*fake_HashedString_c_str)(HashedString *);
//_ZN12HashedStringC2EPKc
#endif //MCENGINE_FAKE_HASHEDSTRING_H
