//
// Created by 30225 on 2023/7/26.
//

#ifndef MCENGINE_HASHEDSTRINGFAKER_HPP
#define MCENGINE_HASHEDSTRINGFAKER_HPP


//This header template file is generated by Disassembler.

#include <string>
#include "headers/mojang/HashedString.h"


//fake区
extern HashedString * (*fake_HashedString_HashedString)(char *const);
extern const char *(*fake_HashedString_c_str)(HashedString *);
extern std::string (*fake_HashedString_getString)(HashedString *);
//_ZN12HashedStringC2EPKc
#endif //MCENGINE_HASHEDSTRINGFAKER_HPP
